### ISSUE TITLE
The newly designed Evince icons should also be visible in the Applications Menu and in the PDF file properties of Files

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/evince#30]
### What Happened?

The Application Menu and the properties view in Files still use the old icon design.

### Steps to Reproduce

1. Open the Application Menu and search for Evince or open the properties of a PDF file in Files.

### Expected Behavior

Here is what I have installed. It shows the new design in AppCenter. This is the version of Evince that was simply updated based on a fresh OS installation. Side observation: No screenshots are displayed in AppCenter.

![Screenshot](https://user-images.githubusercontent.com/46536067/142743065-a1f24521-98f8-41db-9c6c-ad28cebd6b5a.png)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by Marukesu** [comment]
@4jNsY6fCVqZv can you run `flatpak info org.gnome.Evince` and confirm that the installed branch is `master`? and if reinstalling it from AppCenter fixes the icon?

The issue seems to be that the system has the deprecated master branch installed instead of stable that has the correct icon, AppCenter is reading the appdata from the stable branch, but I don't know if it's installing `org.gnome.Evince//master` or `org.gnome.Evince//stable`

**Comment by 4jNsY6fCVqZv** [comment]
`flatpak info org.gnome.Evince` shows `Ref: app/org.gnome.Evince/x86_64/stable`

**Comment by 4jNsY6fCVqZv** [comment]
`flatpak info org.gnome.Evince` returns the output:
`ID: org.gnome.Evince
 Ref: app/org.gnome.Evince/x86_64/stable
  Arch: x86_64
  Branch: stable
  Version: 40.3`
Or do you wish the entire output?

**Comment by 4jNsY6fCVqZv** [comment]
Reinstalling in AppCenter does not fix the issue, no.

**Comment by Marukesu** [comment]
Ok, can you check if there's more than one installation of org.gnome.Evince? you can do that by running `flatpak list --app | grep org.gnome.Evince`.

Also check if the version from the ubuntu repositores are installed with `apt list evince --installed`.

I can only reproduce the issue when the flatpak `master` branch is installed, otherwise, i have no clue of what can be, since AppCenter is installing the right version here.

**Comment by 4jNsY6fCVqZv** [comment]
Looks like a single Evince installation exists.
`Evince org.gnome.Evince 40.3 stable appcenter user`

What output do you expect from `apt list evince --installed`?
For me there is just a `Listing.... Done`.

**Comment by 4jNsY6fCVqZv** [comment]
Are the new Evince icons displayed in your Application Menu and also in the Files properties?

**Comment by Marukesu** [comment]
> What output do you expect from `apt list evince --installed`? For me there is just a `Listing.... Done`.

if evince was installed via apt too, it would show a line like this: `evince/focal 3.36.0-2 amd64`

> Are the new Evince icons displayed in your Application Menu and also in the Files properties?

with the stable branch, yes.

**Comment by 4jNsY6fCVqZv** [comment]
The issue can be closed for me after the last monthly system updates. At least for the files properties I can understand that the new file type icon for PDFs only became available after the update. https://github.com/elementary/icons/releases/tag/6.1.0. I don't have an idea why the icon in the Application Menu is also updated now.

**Comment by 4jNsY6fCVqZv** [comment]
> Side observation: No screenshots are displayed in AppCenter.

For Evince 41.3, I now see application screenshots as well.
