### ISSUE TITLE
Revamp 'Note text' function

### ISSUE THREAD

**Issue by kdwk** [elementary/evince#7]
## Problem

![Screenshot from 2021-06-12 14-10-49](https://user-images.githubusercontent.com/39268094/121766968-05e7cc00-cb88-11eb-94be-469035ab0bd3.png)

The 'note text' window looks horribly out of place in the elementary desktop

## Proposal

Add a layer on top of the PDF and just put text boxes there. the user can control whether the background of the text box, the font, etc.

## Prior Art

![IMG_1475](https://user-images.githubusercontent.com/39268094/121767635-f79baf00-cb8b-11eb-83f3-4a5889185dcb.PNG)
_ Adding text in the iPadOS 14 Files app_

**Comment by danrabbit** [comment]
Hey thanks for filing this report. I'm not sure we should really go that deep with patches here. This notes feature looks pretty awful in the upstream GNOME style as well, so this should probably be filed upstream in the Evince tracker in GitLab: https://gitlab.gnome.org/GNOME/evince/-/issues

Closing as "Out of scope" because this appears to be an upstream issue
